6 desativar estudante
emys-alb/votacao-caesi pull request #24
Opened 2022-02-25 00:39 UTC by helenbc

2022-02-25 01:04 UTC, emys-alb requested changes
Ele informa que vai desativar um estudante mesmo se ele já estiver desativado ou não existir

2022-02-26 00:15 UTC, helenbc commented
@emys-alb A verificação se o estudante não existe foi adicionada, entretanto verificar se o estudante já está desativado adiciona uma complexidade que talvez não seja necessária no momento, visto que o banco trata como se o valor realmente tivesse sido novamente mudado e o resultado acaba sendo o mesmo.

2022-02-26 20:14 UTC, emys-alb approved these changes

2022-02-27 00:17 UTC, emys-alb requested changes

2022-02-27 17:57 UTC, helenbc commented on app/Main.hs
> +    | opcao == "7" = desativaEstudante conn
Pronto

2022-02-27 18:00 UTC, emys-alb approved these changes

2022-02-27 18:00 UTC, merged